const en_dict = Object.freeze({
    title: 'Crown Travel',
    brandName: 'Crown Travel',
    navDiscover: 'Discover',
    navAbout: 'About Ha Long Bay',
    navBooking: 'Book Flight',
    btnLogin: 'Login',
    btnRegister: 'Register',
    heroTitle: 'Discover the Wonder of Ha Long Bay',
    heroSubtitle: 'Experience the magic of Vietnam\'s most iconic destination',
    btnExplore: 'Book Your Adventure',
    aboutTitle: 'About Ha Long Bay',
    aboutDescription: 'Ha Long Bay, located in northern Vietnam, is one of the world\'s most stunning natural wonders. With over 1,600 limestone islands rising dramatically from emerald waters, it\'s a UNESCO World Heritage Site that captivates visitors with breathtaking beauty and adventure opportunities.',
    feature1Title: 'Crystal Clear Waters',
    feature1Description: 'Swim in pristine emerald waters surrounded by dramatic limestone cliffs.',
    feature2Title: 'Island Hopping',
    feature2Description: 'Explore hundreds of scenic islands and hidden caves by traditional boat.',
    feature3Title: 'Unforgettable Sunsets',
    feature3Description: 'Witness breathtaking sunsets from the water as day fades into dusk.',
    feature4Title: 'Adventure Activities',
    feature4Description: 'Rock climbing, kayaking, and diving for the thrill-seekers.',
    bookingTitle: 'Book Your Flight',
    bookingSubtitle: 'Start your journey to Ha Long Bay today',
    labelFrom: 'From',
    labelTo: 'To',
    labelDeparture: 'Departure Date',
    labelReturn: 'Return Date',
    labelPassengers: 'Passengers',
    labelClass: 'Class',
    placeholderFrom: 'Departure City',
    placeholderTo: 'Ha Long Bay, Vietnam',
    optionEconomy: 'Economy',
    optionPremium: 'Premium Economy',
    optionBusiness: 'Business',
    optionFirst: 'First Class',
    btnSearch: 'Search Flights',
    oneWay: "One way",
    correctlyRepeatPassword: "The repeated password must match the original password.",   
    userCreationSuccess: "User successfully created!",
    userCreationError: "An error occurred while creating the user, please try again.",
    userAlreadyExists: "A user with this email already exists.",
    wrongPassword: "Incorrect password",
    noUser: "There is no user registered with this email.",
    flightSearchComplete: "Flight search complete",
    bookingCompleted: "Your experience with Crown Travel begins now. This fictional itinerary is ready to inspire your next story.",
    selectPackageRequired: "Please select a package before confirming the booking.",
    reservationReceived: "Reservation received — total {total}. Our Crown Travel team will contact you to finalize the details.",
    selectedPackageNone: "No package selected",
    selectPackage: "Select",
    confirmReservation: "Confirm reservation",
    priceSubtotal: "Subtotal",
    priceTaxes: "Taxes (10%)",
    priceService: "Service (5%)",
    priceTotal: "Total",

    enterDepartureCity: "Please specify the departure city and date before searching for flights.",
    incompleteDetails: "Incomplete details",
    passanger: "passenger",
    passangers: "passengers",
    password: "Password:",
    repeatPassword: "Repeat password:",
    username: "Username: ",
    halongResume: "UNESCO World Heritage site · Thousands of islands and unique karst formations · Natural, tourist, and cultural symbol of Vietnam",
    halongDesc1: "\"Where the rock meets the sea\" - unique limestone scenery over emerald waters.",
    halongDesc2: "Over 1,600 islands and rock formations that make up one of Vietnam's most iconic places.",
    halongDesc3: "Floating villages, secret caves, and kayaking trips in serene environments.",
    halongDesc4: "Humid subtropical climate: best to visit between March and May or September and November.",
    halongFeatureDesc1: "Limestone islets emerging from the sea create unforgettable landscapes.",
    halongFeatureDesc2: "Recognized for its natural and cultural value, the bay is a World Heritage site.",
    halongFeatureDesc3: "Itineraries aboard comfortable ships with meals and entertainment included.",
    halongFeatureDesc4: "Floating villages, local shows, and authentic cuisine for a complete trip.",
    halongFeatureTitle1: "Unique formations",
    halongFeatureTitle2: "UNESCO Heritage",
    halongFeatureTitle3: "Unforgettable cruises",
    halongFeatureTitle4: "Cultural experiences",
    pricesEyebrow: "Exclusive packages",
    duration: "Ha Long Bay in 5 days / 4 nights",
    journeyData: "A complete journey including airport transfers, accommodation, cruise, tours, and guides, with budget or luxury options.",
    packageSummary: "Package summary",
    pricesDesc: "Values per person in Brazilian Reais (BRL), with a full experience from airport arrival to return.",
    item: "Item",
    economicPackage: "Budget package",
    luxuryPackage: "Luxury package",
    economicHotel: "Ha Long Essence Hotel + transfer",
    luxuryHotel: "Radisson Blu Ha Long Bay + transfer",
    cruise: "Cruise",
    economicCruise: "President Cruise + meals and tours",
    luxuryCruise: "Exclusive room with premium services",
    experiences: "Included experiences",
    economicXp: "Sung Sot (Surprise) Cave, kayaking, floating village, and dinner",
    luxuryXp: "Exclusive experiences with fine dining and tai chi",
    economicPrice: "R$ 15,213.00",
    luxuryPrice: "R$ 24,414.00",
    fullPackage: "Full package per person",
    payment: "Upfront or installment payment.",
    staying: "Transportation • accommodation • meals",
    includes: "Tours • guides • cruise",
    economicNote: "Ideal for those who want to enjoy the trip without breaking the bank.",
    luxuryStaying: "Transportation • premium accommodation • meals",
    luxuryIncludes: "Tours • guides • cruise with extra comfort",
    luxuryNote: "Ideal for those seeking comfort, exclusivity, and premium experiences.",
    overallPlan: "General itinerary",
    planText: "5 days and 4 nights filled with memorable experiences",
    planCoverage: "From pickup in Hanoi to airport drop-off, every day is designed to connect culture, scenery, and relaxation.",
    day1: "Arrival and welcome",
    day1Desc: "Reception at Noi Bai International Airport, transfer to hotel, and welcome dinner.",
    day2: "Ha Long Bay cruise",
    day2Desc: "Boarding the cruise, visit to Sung Sot (Surprise) Cave, and onboard meals with breathtaking landscapes.",
    day3: "Island adventure",
    day3Desc: "Kayaking through islands and coves, visiting the Cua Van floating fishing village, and a cultural show.",
    day4: "Ti Top Island",
    day4Desc: "Climb up to the viewpoint with a hike of about 400 steps, return to the harbor, and transfer to the hotel.",
    day5: "Farewell",
    day5Desc: "Farewell with a special breakfast, airport transfer, and return home with great memories.",
    whenToGoEyebrow: "When to go",
    goodClimate: "Inviting weather",
    whenToGo: "Mild temperatures favor cruises, hiking, and water activities between March and May, and September and November.",
    spring: "Spring",
    timespan1: "March to May",
    temp: "18-28ºC",
    fall: "Autumn",
    timespan2: "September to November",
    climateCondition: "Climate and conditions",
    climateDesc: "The climate is humid subtropical, with cold, dry winters and hot, rainy summers. Rain and fog may alter schedules, but the scenery remains stunning.",
    footerCompany: 'Company',
    footerAbout: 'About Us',
    footerCareer: 'Careers',
    footerPress: 'Press',
    footerSupport: 'Support',
    footerContact: 'Contact Us',
    footerFAQ: 'FAQ',
    footerHelp: 'Help Center',
    footerLegal: 'Legal',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    footerCookies: 'Cookie Policy',
    footerCopyright: '© 2026 Crown Travel. All rights reserved.',
});

export default en_dict;
