const es_dict = Object.freeze({
    title: 'Crown Travel',
    brandName: 'Crown Travel',
    navDiscover: 'Descubrir',
    navAbout: 'Sobre Ha Long Bay',
    navBooking: 'Reservar Vuelo',
    btnLogin: 'Iniciar sesión',
    btnRegister: 'Registrarse',
    heroTitle: 'Descubre la maravilla de Ha Long Bay',
    heroSubtitle: 'Experimenta la magia del destino más icónico de Vietnam',
    btnExplore: 'Reserva tu aventura',
    aboutTitle: 'Sobre Ha Long Bay',
    aboutDescription: 'Ha Long Bay, ubicado en el norte de Vietnam, es una de las maravillas naturales más impresionantes del mundo. Con más de 1.600 islas kársticas que emergen de aguas color esmeralda, es un sitio Patrimonio de la Humanidad de la UNESCO que cautiva con su belleza y aventuras.',
    feature1Title: 'Aguas cristalinas',
    feature1Description: 'Nada en aguas color esmeralda rodeadas de acantilados de piedra caliza.',
    feature2Title: 'Recorrido por islas',
    feature2Description: 'Explora cientos de islas y cuevas ocultas en barco tradicional.',
    feature3Title: 'Atardeceres inolvidables',
    feature3Description: 'Disfruta puestas de sol impresionantes mientras el día se desvanece.',
    feature4Title: 'Actividades de aventura',
    feature4Description: 'Escalada, kayak y buceo para los amantes de la emoción.',
    bookingTitle: 'Reserva tu vuelo',
    bookingSubtitle: 'Comienza tu viaje a Ha Long Bay hoy',
    labelFrom: 'Desde',
    labelTo: 'Hasta',
    labelDeparture: 'Fecha de salida',
    labelReturn: 'Fecha de regreso',
    labelPassengers: 'Pasajeros',
    labelClass: 'Clase',
    placeholderFrom: 'Ciudad de salida',
    placeholderTo: 'Ha Long Bay, Vietnam',
    optionEconomy: 'Económica',
    optionPremium: 'Lujo',
    btnSearch: 'Buscar vuelos',
    oneWay: "Solo ida",
    correctlyRepeatPassword: "La contraseña repetida debe ser igual a la contraseña original.",   
    userCreationSuccess: "¡Usuario creado con éxito!",
    userCreationError: "Ocurrió un error al crear el usuario, por favor intenta nuevamente.",
    userAlreadyExists: "Ya existe un usuario registrado con este correo electrónico.",
    wrongPassword: "Contraseña incorrecta",
    noUser: "No existe un usuario con este correo electrónico.",
    flightSearchComplete: "Búsqueda de vuelos completada",
    bookingCompleted: "Tu experiencia con Crown Travel comienza ahora. Este itinerario ficticio está listo para inspirar tu próxima historia.",
    selectPackageRequired: "Por favor seleccione un paquete antes de confirmar la reserva.",
    reservationReceived: "Reserva recibida — total {total}. El equipo de Crown Travel se pondrá en contacto para finalizar los detalles.",
    selectedPackageNone: "Ningún paquete seleccionado",
    selectPackage: "Seleccionar",
    confirmReservation: "Confirmar reserva",
    priceSubtotal: "Subtotal",
    priceTaxes: "Impuestos (10%)",
    priceService: "Servicio (5%)",
    priceTotal: "Total",

    enterDepartureCity: "Por favor especifica la ciudad de salida y la fecha antes de buscar vuelos.",
    incompleteDetails: "Detalles incompletos",
    passanger: "pasajero",
    passangers: "pasajeros",
    password: "Contraseña:",
    repeatPassword: "Repite la contraseña:",
    username: "Nombre de usuario: ",
    halongResume: "Patrimonio mundial de la UNESCO · Miles de islas y formaciones cársticas únicas · Símbolo natural, turístico y cultural de Vietnam",
    halongDesc1: "\"Donde la roca se encuentra con el mar\" - paisajes únicos de piedra caliza sobre aguas esmeralda.",
    halongDesc2: "Más de 1.600 islas y formaciones rocosas que componen uno de los lugares más emblemáticos de Vietnam.",
    halongDesc3: "Aldeas flotantes, cuevas secretas y paseos en kayak en entornos serenos.",
    halongDesc4: "Clima subtropical húmedo: la mejor época para visitar es entre marzo y mayo o entre septiembre y noviembre.",
    halongFeatureDesc1: "Islotes de piedra caliza que emergen del mar creando paisajes inolvidables.",
    halongFeatureDesc2: "Reconocida por su valor natural y cultural, la bahía es patrimonio mundial.",
    halongFeatureDesc3: "Itinerarios a bordo de barcos confortables con comidas y entretenimiento incluidos.",
    halongFeatureDesc4: "Aldeas flotantes, espectáculos locales y gastronomía auténtica para un viaje completo.",
    halongFeatureTitle1: "Formaciones únicas",
    halongFeatureTitle2: "Patrimonio UNESCO",
    halongFeatureTitle3: "Cruceros inolvidables",
    halongFeatureTitle4: "Experiencias culturales",
    pricesEyebrow: "Paquetes exclusivos",
    duration: "Bahía de Ha Long en 5 días / 4 noches",
    journeyData: "Un viaje completo que incluye traslados desde el aeropuerto, alojamiento, crucero, excursiones y guías, con opciones económicas o de lujo.",
    packageSummary: "Resumen de los paquetes",
    pricesDesc: "Precios por persona en Reales Brasileños (BRL), con una experiencia completa desde la llegada al aeropuerto hasta el regreso.",
    item: "Artículo",
    economicPackage: "Paquete económico",
    luxuryPackage: "Paquete de lujo",
    economicHotel: "Ha Long Essence Hotel + traslado",
    luxuryHotel: "Radisson Blu Ha Long Bay + traslado",
    cruise: "Crucero",
    economicCruise: "President Cruise + comidas y excursiones",
    luxuryCruise: "Habitación exclusiva con servicios premium",
    experiences: "Experiencias incluidas",
    economicXp: "Cueva Sorpresa (Sung Sot), kayak, aldea flotante y cena",
    luxuryXp: "Experiencias exclusivas con alta cocina y tai chi",
    economicPrice: "€ 2.584,69",
    luxuryPrice: "€ 4.147,94",
    fullPackage: "Paquete completo por persona",
    payment: "Pago al contado o en cuotas.",
    staying: "Transporte • alojamiento • alimentación",
    includes: "Excursiones • guías • crucero",
    economicNote: "Ideal para quienes quieren disfrutar del viaje sin gastar de más.",
    luxuryStaying: "Transporte • alojamiento premium • alimentación",
    luxuryIncludes: "Excursiones • guías • crucero con máxima comodidad",
    luxuryNote: "Ideal para quienes buscan confort, exclusividad y experiencias premium.",
    overallPlan: "Itinerario general",
    planText: "5 días y 4 noches con experiencias memorables",
    planCoverage: "Desde la recepción en Hanói hasta el traslado de regreso al aeropuerto, cada día está pensado para conectar cultura, paisajes y descanso.",
    day1: "Llegada y bienvenida",
    day1Desc: "Recepción en el Aeropuerto Internacional de Noi Bai, traslado al hotel y cena de bienvenida.",
    day2: "Crucero por la Bahía de Ha Long",
    day2Desc: "Embarque en el crucero, visita a la Cueva Sorpresa y comidas a bordo con paisajes impresionantes.",
    day3: "Aventura entre islas",
    day3Desc: "Paseo en kayak entre islas y calas, visita a la aldea flotante de pescadores Cua Van y espectáculo cultural.",
    day4: "Isla Ti Top",
    day4Desc: "Subida al mirador con una caminata de unos 400 escalones, regreso al puerto y traslado al hotel.",
    day5: "Despedida",
    day5Desc: "Despedida con un desayuno especial, traslado al aeropuerto y regreso con excelentes recuerdos.",
    whenToGoEyebrow: "Cuándo ir",
    goodClimate: "Clima agradable",
    whenToGo: "Las temperaturas suaves favorecen los cruceros, las caminatas y las actividades acuáticas entre marzo y mayo, y de septiembre a noviembre.",
    spring: "Primavera",
    timespan1: "Marzo a mayo",
    temp: "18-28ºC",
    fall: "Otoño",
    timespan2: "Septiembre a noviembre",
    climateCondition: "Clima y condiciones",
    climateDesc: "El clima es subtropical húmedo, con inviernos fríos y secos y veranos cálidos y lluviosos. La lluvia y la niebla pueden alterar la programación, pero el paisaje sigue siendo espectacular.",
    footerCompany: 'Empresa',
    footerAbout: 'Sobre nosotros',
    footerCareer: 'Carreras',
    footerPress: 'Prensa',
    footerSupport: 'Soporte',
    footerContact: 'Contáctanos',
    footerFAQ: 'Preguntas frecuentes',
    footerHelp: 'Centro de ayuda',
    footerLegal: 'Legal',
    footerPrivacy: 'Política de privacidad',
    footerTerms: 'Términos del servicio',
    footerCookies: 'Política de cookies',
    footerCopyright: '© 2026 Crown Travel. Todos los derechos reservados.',
});

export default es_dict;
