const pt_dict = Object.freeze({
    title: 'Crown Travel',
    brandName: 'Crown Travel',
    navDiscover: 'Descobrir',
    navAbout: 'Sobre Ha Long Bay',
    navBooking: 'Reservar Voo',
    btnLogin: 'Login',
    btnRegister: 'Cadastrar-se',
    heroTitle: 'Descubra a maravilha de Ha Long Bay',
    heroSubtitle: 'Experimente a magia do destino mais icônico do Vietnã',
    btnExplore: 'Reserve sua aventura',
    aboutTitle: 'Sobre Ha Long Bay',
    aboutDescription: 'Ha Long Bay, localizado no norte do Vietnã, é uma das maravilhas naturais mais impressionantes do mundo. Com mais de 1.600 ilhas de calcário surgindo em águas esmeralda, é um Patrimônio Mundial da UNESCO que cativa visitantes com sua beleza e oportunidades de aventura.',
    feature1Title: 'Águas cristalinas',
    feature1Description: 'Nade em águas esmeralda cercadas por dramáticos penhascos de calcário.',
    feature2Title: 'Passeio de ilhas',
    feature2Description: 'Explore centenas de ilhas e cavernas escondidas em barco tradicional.',
    feature3Title: 'Pôr do sol inesquecíveis',
    feature3Description: 'Presencie pores do sol impressionantes enquanto o dia se transforma.',
    feature4Title: 'Atividades de aventura',
    feature4Description: 'Escalada, caiaque e mergulho para os amantes de emoção.',
    bookingTitle: 'Reserve seu voo',
    bookingSubtitle: 'Comece sua jornada para Ha Long Bay hoje',
    labelFrom: 'De',
    labelTo: 'Para',
    labelDeparture: 'Data de partida',
    labelReturn: 'Data de retorno',
    labelPassengers: 'Passageiros',
    labelClass: 'Classe',
    placeholderFrom: 'Cidade de partida',
    placeholderTo: 'Ha Long Bay, Vietnã',
    optionEconomy: 'Econômica',
    optionPremium: 'Luxo',
    btnSearch: 'Buscar voos',
    oneWay: "Apenas ida",
    correctlyRepeatPassword: "A senha repetida deve ser igual a senha original.",   
    userCreationSuccess: "Usuário criado com sucesso!",
    userCreationError: "Ocorreu um erro ao criar o usuário, tente novamente.",
    userAlreadyExists: "Já existe um usuário com este email registrado.",
    wrongPassword: "Senha incorreta",
    noUser: "Não existe um usuário com este email.",
    flightSearchComplete: "Pesquisa de voo completa",
    bookingCompleted: "Sua experiência com a Crown Travel começa agora. Este roteiro fictício está pronto para inspirar sua próxima história.",
    selectPackageRequired: "Por favor selecione um pacote antes de confirmar a reserva.",
    reservationReceived: "Reserva recebida — total {total}. A equipe da Crown Travel entrará em contato para finalizar os detalhes.",
    selectedPackageNone: "Nenhum pacote selecionado",
    selectPackage: "Selecionar",
    confirmReservation: "Confirmar reserva",
    priceSubtotal: "Subtotal",
    priceTaxes: "Taxas",
    priceService: "Serviço",
    priceTotal: "Total",

    enterDepartureCity: "Por favor especifique a cidade de saída e a data antes de pesquisar por voos.",
    incompleteDetails: "Detalhes incompletos",
    passanger: "passageiro",
    passangers: "passageiros",
    password: "Senha:",
    repeatPassword: "Repita a senha:",
    username: "Nome de usuário: ",
    halongResume: "Patrimônio mundial da UNESCO · Milhares de ilhas e formações cársticas únicas · Símbolo natural, turístico e cultural do Vietnã",
    halongDesc1: "\"Onde a pedra enocntra o mar\" - cenários únicos de calcário sobre águas esmeralda.",
    halongDesc2: "Mais de 1.600 ilhas e formações rochosas que compõem um dos lugares mais emblemáticos do Vietnã.",
    halongDesc3: "Vilas flutuantes, grutas secretas e passeios de caiaque em ambientes serenos.",
    halongDesc4: "Clima subtropical úmido: melhor visitar entre março e maio ou setembro e novembro.",
    halongFeatureDesc1: "Calhaus de calcário emergindo do mar criam paisagens inesquecíveis.",
    halongFeatureDesc2: "Reconhecida por seu valor natural e cultural, a baía é patrimônio mundial.",
    halongFeatureDesc3: "Roteiros a bordo de navios confortáveis com refeições e entretenimento inclusos.",
    halongFeatureDesc4: "Vilas flutuantes, shows locais e culinária autêntica para uma viagem completa.",
    halongFeatureTitle1: "Formações únicas",
    halongFeatureTitle2: "Patrimônio UNESCO",
    halongFeatureTitle3: "Cruzeiros inesquecíveis",
    halongFeatureTitle4: "Experiências culturais",
    pricesEyebrow: "Pacotes exclusivos",
    duration: "Baía de Ha Long em 5 dias / 4 noites",
    journeyData: "Uma jornada completa entre o aeroporto, hospedagem, cruzeiro, passeios e guias, com opções econômicas ou de luxo.",
    packageSummary: "Resumo dos pacotes",
    pricesDesc: "Valores por pessoa em Reais (BRL), com experiência completa do aeroporto ao retorno.",
    spendingBreakdownTitle: "Detalhamento de gastos",
    spendingBreakdownDesc: "Veja cada item incluído em cada pacote e o valor correspondente.",
    item: "Item",
    package: "Pacote",
    price: "Preço",
    flight: "Passagem aérea",
    hotel: "Hospedagem",
    transport: "Transporte",
    cruiseItem: "Cruzeiro",
    food: "Alimentação",
    totalComplete: "Total completo",
    economicPackage: "Pacote econômico",
    luxuryPackage: "Pacote de luxo",
    economicHotel: "Ha Long Essence Hotel + traslado",
    luxuryHotel: "Radisson Blu Ha Long Bay + traslado",
    cruise: "Cruzeiro",
    economicCruise: "President Cruise + refeições e passeios",
    luxuryCruise: "Quarto exclusivo com serviços premium",
    experiences: "Experiências inclusas",
    economicXp: "Gruta da Surpresa, kayak, vila flutuante e jantar",
    luxuryXp: "Experiências exclusivas com culinária e tai chi",
    economicPrice: "R$ 15.213,00",
    luxuryPrice: "R$ 24.414,00",
    fullPackage: "Pacote completo por pessoa",
    payment: "Pagamento à vista ou parcelado.",
    staying: "Transporte • hospedagem • alimentação",
    includes: "Passeios • guias • cruzeiro",
    economicNote: "Ideal para quem quer aproveitar a viagem sem pesar no bolso.",
    luxuryStaying: "Transporte • hospedagem premium • alimentação",
    luxuryIncludes: "Passeios • guias • cruzeiro com conforto",
    luxuryNote: "Ideal para quem busca conforto, exclusividade e experiências premium.",
    overallPlan: "Roteiro geral",
    planText: "5 dias e 4 noites com experiências marcantes",
    planCoverage: "Do recebimento em Hanói ao retorno ao aeroporto, cada dia é pensado para conectar cultura, paisagem e descanso.",
    day1: "Chegada e boas-vindas",
    day1Desc: "Recepção no Aeroporto Internacional de Noi Bai, traslado ao hotel e jantar de boas-vindas.",
    day2: "Cruzeiro pela Baía de Ha Long",
    day2Desc: "Embarque no cruzeiro, visita à Gruta da Surpresa e refeições a bordo com paisagens de tirar o fôlego.",
    day3: "Aventura entre ilhas",
    day3Desc: "Kayak entre ilhas e enseadas, encontro com a vila flutuante de pescadores Cua Van e show cultural.",
    day4: "Ilha Ti Top",
    day4Desc: "Subida ao mirante com caminhada de cerca de 400 degraus e retorno ao porto com traslado ao hotel.",
    day5: "Encerramento",
    day5Desc: "Despedida com café da manhã especial, traslado ao aeroporto e retorno com boas memórias.",
    whenToGoEyebrow: "Quando ir",
    goodClimate: "Clima que convida",
    whenToGo: "Temperaturas amenas favorecem cruzeiros, caminhadas e atividades aquáticas entre março e maio e setembro e novembro.",
    spring: "Primavera",
    timespan1: "Março a maio",
    temp: "18-28ºC",
    fall: "Outono",
    timespan2: "Setembro a novembro",
    climateCondition: "Clima e condições",
    climateDesc: "O clima é subtropical úmido, com invernos frios e secos e verões quentes e chuvosos. Chuvas e neblina podem alterar a programação, mas o cenário permanece deslumbrante.",
    footerCompany: 'Empresa',
    footerAbout: 'Sobre nós',
    footerCareer: 'Carreiras',
    footerPress: 'Imprensa',
    footerSupport: 'Suporte',
    footerContact: 'Contate-nos',
    footerFAQ: 'FAQ',
    footerHelp: 'Central de Ajuda',
    footerLegal: 'Legal',
    footerPrivacy: 'Política de Privacidade',
    footerTerms: 'Termos de Serviço',
    footerCookies: 'Política de Cookies',
    footerCopyright: '© 2026 Crown Travel. Todos os direitos reservados.',
});

export default pt_dict;
